//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TangoClubUploader.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TangoClub
    {
        public string CodigTrack { get; set; }
        public string Tema { get; set; }
        public string Fecha { get; set; }
        public string Album { get; set; }
        public string CodigoAlbum { get; set; }
        public string Sello { get; set; }
        public string Estilo { get; set; }
        public string Genero { get; set; }
        public string Interprete { get; set; }
        public string Orquesta { get; set; }
        public string Compositor { get; set; }
        public string Vocalista { get; set; }
        public string Autor { get; set; }
        public Nullable<short> Track { get; set; }
        public string Path { get; set; }
    }
}
