//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TangoClubUploader.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TangoClub
    {
        public string CodigTrack { get; set; }
        public string Tema { get; set; }
        public string Fecha { get; set; }
        public string Album { get; set; }
        public string CodigoAlbum { get; set; }
        public string Sello { get; set; }
        public string Estilo { get; set; }
        public string Genero { get; set; }
        public string Interprete { get; set; }
        public string Orquesta { get; set; }
        public string Compositor { get; set; }
        public string Vocalista { get; set; }
        public string Autor { get; set; }
        public Nullable<int> track { get; set; }
        public string path { get; set; }
    }
}
